version: "3.9"
services:
  cloudflared:
    container_name: cloudflared
    restart: unless-stopped
    image: cloudflare/cloudflared:latest
    command: proxy-dns
    environment:
      - "TUNNEL_DNS_UPSTREAM=https://1.1.1.1/dns-query,https://1.0.0.1/dns-query,https://9.9.9.9/dns-query"
      - "TUNNEL_DNS_PORT=5053"
      - "TUNNEL_DNS_ADDRESS=0.0.0.0"
    networks:
      internal:
        ipv4_address: "172.30.9.2"
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "5335:53/tcp"
      - "5335:53/udp"
      #- "67:67/udp"
      - "8008:80/tcp"
      - "7443:443/tcp"
    environment:
      TZ: 'Europe/Berlin'
      # FTLCONF_webserver_api_password: 'very_security_password_if_want_to_change'
      FTLCONF_dns_listeningMode: 'all'
      FTLCONF_dns_upstreams: "172.30.9.2#5053"
    volumes:
      - './etc-pihole:/etc/pihole'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      internal:
        ipv4_address: "172.30.9.3"
    depends_on:
      - cloudflared
networks:
  internal:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: "172.30.9.0/29"
